SELECT 
    EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
    MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA E
JOIN (
    SELECT 
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)
) YEARLY_MAX 
ON EXTRACT(YEAR FROM E.DIFFERENTIATION_DATE) = YEARLY_MAX.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;